apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
      grok {
        match => { "message" => "%{COMBINEDAPACHELOG}" }
      }
      date {
        match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
      }
    }

    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "filebeat-%{+YYYY.MM.dd}"
        #user => "elastic"
        #password => "changeme"
      }
    }

  filebeat.yml: |
    filebeat.inputs:

    - type: filestream
      enabled: true
      paths:
        - /usr/share/filebeat/test/*.log
    filebeat.config.modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: false


    setup.template.settings:
      index.number_of_shards: 1
      #index.codec: best_compression
      #_source.enabled: false

    output.logstash:
      # The Logstash hosts
      hosts: ["logstash:5044"]

    # output.elasticsearch:
    #   # Array of hosts to connect to.
    #   hosts: ["elasticsearch:9200"]

    processors:
      - add_host_metadata:
          when.not.contains.tags: forwarded
      - add_cloud_metadata: ~
      - add_docker_metadata: ~
      - add_kubernetes_metadata: ~
