apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test
spec:
  hosts:
  - "test.example.com"
  gateways:
  - test-gateway
  http:
  - match:
    - uri:
        prefix: /
      headers:
        cookie:
          regex: ^(.*?;)?(version=v2)(;.*)?$
    route:
    - destination:
        port:
          number: 80
        host: test
        subset: v2
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: test
        subset: v1
  # - match:
  #   - uri:
  #       prefix: /
  #   route:
  #   - destination:
  #       port:
  #         number: 80
  #       host: test
  #       subset: v1
  #     weight: 20
  #   - destination:
  #       port:
  #         number: 80
  #       host: test
  #       subset: v2
  #     weight: 80