kind: pipeline
type: docker
name: default


platform:
  os: linux
  arch: amd64
  
pipeline:
  test:
      image: golang
      commands:
      - go test ./...
  build:
      image: golang
      commands:
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build

  publish:
    image: plugins/docker
    dockerfile: ./Dockerfile
    registry: registry.cn-shenzhen.aliyuncs.com
    repo: registry.cn-shenzhen.aliyuncs.com/liuyuexclusive/future.srv.basic
    username: "liuyuexclusive@hotmail.com"
    password: "qwert123"
    tags:
      - latest   

  # deploy:
  #   image: appleboy/drone-ssh # 用于连接服务器
  #   host: 
  #     - 192.168.0.102
  #   port: 22
  #   username: aaa
  #   password: bbb
  #   script:
  #     - export PATH=/usr/local/bin:$PATH
  #     - docker stop future.srv.basic_1
  #     - docker rm future.srv.basic_1
  #     - docker run -d --net=utils_default --name=future.srv.basic_1 registry.cn-shenzhen.aliyuncs.com/liuyuexclusive/future.srv.basic:latest