global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s
  alerting:
    alertmanagers:
    - static_configs:
      - targets: []
      scheme: http
      timeout: 10s
  scrape_configs:
  - job_name: APIGW
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /basic/metrics
    scheme: http
    static_configs:
    - targets:
      - 49.232.166.55:9000  #192.168.0.199为本机ip， 本机127.0.0.1在容器中无法访问到