apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /Users/yu/docker_volumes
      containerPath: /www
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock