apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports: 
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: v1
            - mountPath: /docker-entrypoint-initdb.d/future_postgres.sql
              name: v2
          env:
            - name: POSTGRES_PASSWORD
              value: "123456"
      volumes:
        - name: v1
          hostPath: 
            path: /Users/yu/docker_volumes/postgres
            type: DirectoryOrCreate

        - name: v2
          hostPath:
            path: /Users/yu/golang/utils/future_postgres.sql
            type: File


--- 

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  type: NodePort
  ports:
  - protocol: TCP
    port: 30003
    targetPort: 5432
    nodePort: 30003
