apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: stateful
  name: etcd
spec:
  serviceName: "etcd"
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: bitnami/etcd:latest
          ports: 
            - containerPort: 2379
            - containerPort: 2380
          env:
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: "http://etcd:2379"
          volumeMounts:
            - name: etcd
              mountPath: /opt/bitnami/etcd/data
  volumeClaimTemplates:
    - metadata:
        name: etcd
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi


---

apiVersion: v1
kind: Service
metadata:
  namespace: stateful
  name: etcd
spec:
  selector:
    app: etcd
  ports:
    - protocol: TCP
      port: 2379
      targetPort: 2379
