apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: stateful
  name: kafka
spec:
  serviceName: "kafka"
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:latest
          ports: 
            - containerPort: 2181
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
        - name: kafka
          image: bitnami/kafka:latest
          ports: 
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://127.0.0.1:9092"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "localhost:2181"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
          volumeMounts:
            - name: kafka
              mountPath: /bitnami/kafka
  volumeClaimTemplates:
    - metadata:
        name: kafka
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  namespace: stateful
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092