Name: "srv.testClient"
Lease: 5
IP: 172.254.0.148
Port: "8080"
Address: ""
ConnStr: host=172.254.0.148 port=5432 password=123456 sslmode=disable user=postgres dbname=evolve
ElasticURL: http://172.254.0.148:9200
ETCDAddress: 
  - 172.254.0.148:2379
JaegerAddress: 172.254.0.148:6831
NatsAddress: 172.254.0.148:4222
RedisAddress: 172.254.0.148:6379
LogPath: "./log"
LogLevel: "debug"
AuthServiceName: "srv.auth"
TLS: 
  CertFile: "/Users/liuyu/golang/utils/ssl/server_cert.pem"
  KeyFile: "/Users/liuyu/golang/utils/ssl/server_key.pem"
  CACertFile: "/Users/liuyu/golang/utils/ssl/server_ca_cert.pem"
  ServerNameOverride: "test.example.com"

