Name: "srv.basic"
Lease: 5
IP: 192.168.199.246
Port: "8080"
Address: ""
ConnStr: host=192.168.199.246 port=5432 password=123456 sslmode=disable user=postgres dbname=evolve
ElasticURL: http://192.168.199.246:9200
ETCDAddress: 
  - 192.168.199.246:2379
JaegerAddress: 192.168.199.246:6831
NatsAddress: 192.168.199.246:4222
RedisAddress: 192.168.199.246:6379
LogPath: "./log"
LogLevel: "debug"
AuthServiceName: "srv.auth"
TLS: 
  CertFile: "/Users/liuyu/golang/utils/ssl/server_cert.pem"
  KeyFile: "/Users/liuyu/golang/utils/ssl/server_key.pem"
  CACertFile: "/Users/liuyu/golang/utils/ssl/server_ca_cert.pem"
  ServerNameOverride: "test.example.com"

