.PHONY:proto
proto:
	protoc --go_out=:. --go-grpc_out=. ./proto/role/role.proto
	protoc --go_out=:. --go-grpc_out=. ./proto/user/user.proto
	protoc --go_out=:. --go-grpc_out=. ./proto/message/message.proto