apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stateless
  name: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:8.0.0
          ports: 
            - containerPort: 5601
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
      volumes:
        - name: config-volume
          configMap: 
            name: kibana-config


--- 

apiVersion: v1
kind: Service
metadata:
  namespace: stateless
  name: kibana
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601

