  # gitea:
  #   image: gitea/gitea
  #   container_name: gitea
  #   environment:
  #     - USER_UID=1000
  #     - USER_GID=1000
  #     - GITEA__database__DB_TYPE=postgres
  #     - GITEA__database__HOST=10.86.12.184:5432
  #     - GITEA__database__NAME=gitea
  #     - GITEA__database__USER=postgres
  #     - GITEA__database__PASSWD=123456
  #   depends_on: 
  #     - postgres
  #   restart: always
  #   volumes:
  #     - $HOME/docker_volumes/gitea:/data
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   ports:
  #     - "3000:3000"
  #     - "222:22"

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: stateful
  name: gitea
spec:
  serviceName: gitea
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image:  gitea/gitea
          ports: 
            - containerPort: 3000
            - containerPort: 22
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
            - name: GITEA__database__DB_TYPE
              value: postgres
            - name: GITEA__database__HOST
              value: postgres:5432
            - name: GITEA__database__NAME
              value: gitea
            - name: GITEA__database__USER
              value: postgres
            - name: GITEA__database__PASSWD
              value: "123456"
          volumeMounts:
            - name: gitea
              mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: gitea
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi

--- 

apiVersion: v1
kind: Service
metadata:
  namespace: stateful
  name: gitea
spec:
  selector:
    app: gitea
  ports:
    - name: p1
      port: 3000
      targetPort: 3000
    - name: p2
      port: 22
      targetPort: 22
